/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omarg
 */

public class Registro_Consumidor extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    Statement st;
    CallableStatement call;
    String id;

    public void Conectar() {
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"
                    + "databaseName=profeco;user=sa;password=sasa;");
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Creates new form Consumidor
     */
    public Registro_Consumidor() {
        initComponents();
        this.setSize(900,400);
        this.setLocationRelativeTo(null);
        Conectar();
    }
    
    public void Guardar(){
        try {
            String cor,pass,nom,ap,am,ed,sex,cal,col,mun,cd;
            cor=txtCorreo.getText();
            nom=txtNom.getText();
            pass=txtCon1.getText();
            ap=txtAp.getText();
            am=txtAm.getText();
            ed=txtEdad.getText();
            sex=CbxSexo.getSelectedItem().toString();
            cal=txtCa.getText();
            col=txtCol.getText();
            mun=txtMun.getText();
            cd=txtCd.getText();
            
            call=con.prepareCall("{call add_cons (?,?,?,?,?,?,?,?,?,?,?)}");
            call.setString(1,cor );
            call.setString(2,pass );
            call.setString(3,nom );
            call.setString(4,ap );
            call.setString(5,am );
            call.setString(6,ed );
            call.setString(7,sex );
            call.setString(8,cal );
            call.setString(9,col );
            call.setString(10,mun );
            call.setString(11,cd );
            call.execute();
            JOptionPane.showMessageDialog(null, "Te has registrado correctamente!\nInicia sesion");
            dispose();
            new Login().setVisible(true);
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No ha guardado correctamente el registro","Ha surgido un error",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Registro_Consumidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtAp = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCont2 = new javax.swing.JPasswordField();
        txtCon1 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        panel1 = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        txtMun = new javax.swing.JTextField();
        txtCol = new javax.swing.JTextField();
        txtCd = new javax.swing.JTextField();
        txtCa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CbxSexo = new javax.swing.JComboBox<>();
        txtAm = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(930, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Materno");
        jLabel2.setAutoscrolls(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Paterno");
        jLabel3.setAutoscrolls(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONSUMIDOR");
        jLabel4.setAutoscrolls(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        jLabel5.setAutoscrolls(true);
        jLabel5.setEnabled(false);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 110, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");
        jLabel8.setAutoscrolls(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtNom.setBackground(new java.awt.Color(39, 40, 50));
        txtNom.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtNom.setForeground(new java.awt.Color(255, 255, 255));
        txtNom.setFocusTraversalPolicyProvider(true);
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        txtEdad.setBackground(new java.awt.Color(39, 40, 50));
        txtEdad.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(255, 255, 255));
        txtEdad.setFocusTraversalPolicyProvider(true);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 150, -1));

        txtAp.setBackground(new java.awt.Color(39, 40, 50));
        txtAp.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtAp.setForeground(new java.awt.Color(255, 255, 255));
        txtAp.setFocusTraversalPolicyProvider(true);
        txtAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApActionPerformed(evt);
            }
        });
        getContentPane().add(txtAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, -1));

        txtCorreo.setBackground(new java.awt.Color(39, 40, 50));
        txtCorreo.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFocusTraversalPolicyProvider(true);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 324, -1));

        jLabel6.setBackground(new java.awt.Color(39, 40, 50));
        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Colonia");
        jLabel6.setAutoscrolls(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel9.setBackground(new java.awt.Color(39, 40, 50));
        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Municipio");
        jLabel9.setAutoscrolls(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        jLabel10.setBackground(new java.awt.Color(39, 40, 50));
        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ciudad");
        jLabel10.setAutoscrolls(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.setAutoscrolls(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 6, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña");
        jLabel11.setAutoscrolls(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Confirma Contraseña");
        jLabel12.setAutoscrolls(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        txtCont2.setBackground(new java.awt.Color(39, 40, 50));
        txtCont2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txtCont2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCont2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 239, -1));

        txtCon1.setBackground(new java.awt.Color(39, 40, 50));
        txtCon1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txtCon1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 239, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Calle");
        jLabel13.setAutoscrolls(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, -1));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 10));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 310, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Edad");
        jLabel14.setAutoscrolls(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 70, -1));

        txtMun.setBackground(new java.awt.Color(39, 40, 50));
        txtMun.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtMun.setForeground(new java.awt.Color(255, 255, 255));
        txtMun.setFocusTraversalPolicyProvider(true);
        txtMun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunActionPerformed(evt);
            }
        });
        getContentPane().add(txtMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 330, -1));

        txtCol.setBackground(new java.awt.Color(39, 40, 50));
        txtCol.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtCol.setForeground(new java.awt.Color(255, 255, 255));
        txtCol.setFocusTraversalPolicyProvider(true);
        txtCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColActionPerformed(evt);
            }
        });
        getContentPane().add(txtCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 320, -1));

        txtCd.setBackground(new java.awt.Color(39, 40, 50));
        txtCd.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtCd.setForeground(new java.awt.Color(255, 255, 255));
        txtCd.setFocusTraversalPolicyProvider(true);
        txtCd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCdActionPerformed(evt);
            }
        });
        getContentPane().add(txtCd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, -1));

        txtCa.setBackground(new java.awt.Color(39, 40, 50));
        txtCa.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtCa.setForeground(new java.awt.Color(255, 255, 255));
        txtCa.setFocusTraversalPolicyProvider(true);
        txtCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sexo");
        jLabel15.setAutoscrolls(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 70, -1));

        CbxSexo.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        CbxSexo.setForeground(new java.awt.Color(255, 255, 255));
        CbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "M" }));
        CbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxSexoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 80, -1));

        txtAm.setBackground(new java.awt.Color(39, 40, 50));
        txtAm.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txtAm.setForeground(new java.awt.Color(255, 255, 255));
        txtAm.setFocusTraversalPolicyProvider(true);
        txtAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmActionPerformed(evt);
            }
        });
        getContentPane().add(txtAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 150, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 3));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Guardar();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunActionPerformed

    private void txtColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColActionPerformed

    private void txtCdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCdActionPerformed

    private void txtCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaActionPerformed

    private void txtAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmActionPerformed

    private void CbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxSexoActionPerformed

    private void txtApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Consumidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Consumidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Consumidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Consumidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Consumidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxSexo;
    private javax.swing.JLabel Fondo;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtAm;
    private javax.swing.JTextField txtAp;
    private javax.swing.JTextField txtCa;
    private javax.swing.JTextField txtCd;
    private javax.swing.JTextField txtCol;
    private javax.swing.JPasswordField txtCon1;
    private javax.swing.JPasswordField txtCont2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMun;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
